# Generated by Django 4.1.4 on 2022-12-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gameplay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="modified_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Last Player Turn"
            ),
        ),
    ]
